name: local_filesystem_example
description: "A pure-Dart CLI example that installs and runs the MCP Node.js filesystem server to list and sort files."
publish_to: 'none'

environment:
  sdk: ^3.12.0

dependencies:
  dart_mcp_core:
    path: ../../../dart_mcp_core
  universal_io: ^2.3.1
