name: mcp_playground_flutter_example
description: "A consolidated showcase demonstrating MCP Playground Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mcp_playground_flutter:
    path: ../
  mcp_playground_dart: ^0.3.2
  mcp_playground_ui: ^0.4.0
  mcp_playground_shared_tools:
    path: shared_tools
  http: ^1.6.0
  dartssh2: ^2.18.0
  mime: ^2.0.0
  fl_chart: ^1.2.0
  material_ui: ^1.3.0
#dependency_overrides:
#  mcp_playground_dart:
#    path: ../../mcp_playground_dart
#  mcp_playground_ui:
#    path: ../../mcp_playground_ui
#  mcp_playground_flutter:
#    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - ../../.env
