import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:genui/genui.dart' hide ChatMessage;
import 'package:mcp_playground_dart/mcp_playground_dart.dart' hide LocalMCPClient;
import 'package:mcp_playground_ui/mcp_playground_ui.dart';
import 'package:uuid/uuid.dart';

import 'genui_catalog.dart';
import 'genui_chat_controller.dart';

String _mimeFromExtension(String name) => mimeFromExtension(name);

/// An interactive GenUI AI Agent Playground widget for Flutter.
///
/// Connects to various LLM providers, registers Dart-native tools,
/// remote HTTP/S MCP servers, local MCP subprocesses, and dynamically renders
/// interactive Flutter widgets generated by the model.
class GenuiMcpPlayground extends StatefulWidget {
  /// Default LLM setup parameters.
  final LlmConfig? initialLlmConfig;

  /// Default list of HTTP/HTTPS MCP servers to connect to.
  final List<McpServerConfig>? initialServers;

  /// Optional list of local MCP servers to auto-initialize/install.
  final List<LocalMcpServerSetup>? initialLocalMcpServers;

  /// Optional delegate to customize settings save/load operations.
  final McpPlaygroundStorageDelegate? storageDelegate;

  /// Custom list of internal, Dart-native tools to register.
  final List<McpLocalTool>? customLocalTools;

  /// Whether to disable opening the configuration dialog when LLM is not configured.
  final bool disableConfigDialog;

  /// Optional locale override ('en' or 'de').
  final String? locale;

  /// Whether to print clean console logs for key events.
  final bool enableLogging;

  /// Optional list of GenUI catalog items to register.
  final List<GenuiCatalogItemDefinition>? genuiCatalogItems;

  /// Optional custom GenUI catalog.
  final Catalog? genuiCatalog;

  /// Optional catalog JSON string.
  final String? genuiCatalogJson;

  /// Whether to show the Agent Inspector side panel and toggle button. Defaults to true.
  final bool showAgentInspector;

  /// Optional initial system prompt.
  final String? initialSystemPrompt;

  /// Optional list of tool names to pre-select as active on startup.
  final List<String>? initialEnabledTools;

  /// Creates a new [GenuiMcpPlayground] widget instance.
  const GenuiMcpPlayground({
    super.key,
    this.initialLlmConfig,
    this.initialServers,
    this.initialLocalMcpServers,
    this.storageDelegate,
    this.customLocalTools,
    this.disableConfigDialog = false,
    this.locale,
    this.enableLogging = false,
    this.genuiCatalogItems,
    this.genuiCatalog,
    this.genuiCatalogJson,
    this.showAgentInspector = true,
    this.initialSystemPrompt,
    this.initialEnabledTools,
  });

  @override
  State<GenuiMcpPlayground> createState() => _GenuiMcpPlaygroundState();
}

class _GenuiMcpPlaygroundState extends State<GenuiMcpPlayground> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  final _inputCtrl = TextEditingController();
  final _scrollCtrl = ScrollController();
  final List<MessageAttachment> _attachments = [];

  late PlaygroundController _controller;
  late McpPlaygroundLocalizations _l10n;

  bool _playgroundStarted = false;
  String? _loadedSetupId;
  double _chatFraction = 0.7;
  bool _inspectorVisible = true;
  McpGenuiChatController? _genuiController;

  // Setup form states
  final _systemPromptCtrl = TextEditingController();
  final _initialPromptCtrl = TextEditingController();
  final bool _chatMode = false;

  // Custom LLM Override state
  bool _useCustomLlm = false;
  LlmProvider _customProvider = LlmProvider.none;
  final _customModelCtrl = TextEditingController();
  final _customApiKeyCtrl = TextEditingController();
  final _customBaseUrlCtrl = TextEditingController();

  final _customTempCtrl = TextEditingController(text: '0.2');
  final _customMaxTokensCtrl = TextEditingController(text: '0');
  final _customMaxToolOutputSizeCtrl = TextEditingController(text: '2560000');
  final _customTokenWarningThresholdCtrl = TextEditingController(
    text: '1500000',
  );
  final _customTopKCtrl = TextEditingController();
  final _customTopPCtrl = TextEditingController();
  final _customRepeatPenaltyCtrl = TextEditingController();
  final _customSeedCtrl = TextEditingController();
  bool _customThinking = false;
  bool _customIsSlm = false;
  bool _customIsMultiModal = true;
  bool _customUseNativeTool = true;
  bool _customUseStreaming = false;

  @override
  void initState() {
    super.initState();
    if (widget.initialSystemPrompt != null) {
      _systemPromptCtrl.text = widget.initialSystemPrompt!;
    }
    _controller = PlaygroundController(
      initialLlmConfig: widget.initialLlmConfig,
      initialServers: widget.initialServers,
      customLocalTools: widget.customLocalTools,
      storageDelegate: widget.storageDelegate,
      enableLogging: widget.enableLogging,
    );
    _controller.addListener(_onStateChange);

    WidgetsBinding.instance.addPostFrameCallback((_) async {
      if (widget.initialEnabledTools != null) {
        _controller.updateEnabledTools(widget.initialEnabledTools!.toSet());
      }
      await _checkAndInstallInitialLocalMcpServers();
    });
  }

  void _onStateChange() {
    if (mounted) {
      setState(() {});
      if (_controller.messages.isNotEmpty ||
          (_genuiController?.entries.isNotEmpty ?? false)) {
        Future.delayed(const Duration(milliseconds: 100), _scrollToBottom);
      }
    }
  }

  Future<void> _checkAndInstallInitialLocalMcpServers() async {
    final isDesktop =
        !kIsWeb && (Platform.isWindows || Platform.isLinux || Platform.isMacOS);
    if (!isDesktop) return;

    while (_controller.isLoading && mounted) {
      await Future.delayed(const Duration(milliseconds: 100));
    }
    if (!mounted) return;

    final localServersSetup = widget.initialLocalMcpServers;
    if (localServersSetup == null || localServersSetup.isEmpty) return;

    final List<LocalMcpServerSetup> serversToInstall = [];
    final List<McpServerConfig> configsToRegister = [];

    for (final setup in localServersSetup) {
      final existingIdx = _controller.servers.indexWhere(
        (s) => s.name == setup.name,
      );

      McpServerConfig? config;
      bool needsInstall = false;

      if (existingIdx != -1) {
        config = _controller.servers[existingIdx];
        if (setup.reinstall || !config.isInstalled) {
          needsInstall = true;
        }
      } else {
        needsInstall = true;
        config = McpServerConfig(
          id: const Uuid().v4(),
          name: setup.name,
          url: setup.launchArguments ?? '',
          isLocal: true,
          localType: setup.type,
          localInstallMethod: setup.method,
          localPackage: setup.packageOrServerName,
          localCommand: setup.installCommand,
          customLaunchCommand: setup.launchCommand,
          localEnvVars: setup.envVars,
          isInstalled: false,
          enabled: true,
        );
        configsToRegister.add(config);
      }

      if (needsInstall) {
        serversToInstall.add(setup);
      }
    }

    for (final config in configsToRegister) {
      await _controller.addServer(config, autoSelectTools: false);
    }

    if (serversToInstall.isEmpty || !mounted) return;

    await showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => InitialMcpInstallProgressDialog(
        serversToInstall: serversToInstall,
        controller: _controller,
      ),
    );
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _l10n = McpPlaygroundLocalizations.of(
      context,
      overrideLocale: widget.locale,
    );
  }

  @override
  void dispose() {
    _controller.removeListener(_onStateChange);
    _controller.dispose();
    _genuiController?.dispose();
    _inputCtrl.dispose();
    _scrollCtrl.dispose();
    _systemPromptCtrl.dispose();
    _initialPromptCtrl.dispose();
    _customModelCtrl.dispose();
    _customApiKeyCtrl.dispose();
    _customBaseUrlCtrl.dispose();
    _customTempCtrl.dispose();
    _customMaxTokensCtrl.dispose();
    _customMaxToolOutputSizeCtrl.dispose();
    _customTokenWarningThresholdCtrl.dispose();
    _customTopKCtrl.dispose();
    _customTopPCtrl.dispose();
    _customRepeatPenaltyCtrl.dispose();
    _customSeedCtrl.dispose();
    super.dispose();
  }

  void _scrollToBottom() {
    if (_scrollCtrl.hasClients) {
      _scrollCtrl.animateTo(
        _scrollCtrl.position.maxScrollExtent,
        duration: const Duration(milliseconds: 250),
        curve: Curves.easeOut,
      );
    }
  }

  LlmConfig _getActiveLlmConfig() {
    if (_useCustomLlm) {
      return LlmConfig(
        provider: _customProvider,
        model: _customModelCtrl.text.trim(),
        apiKey: _customApiKeyCtrl.text.trim(),
        baseUrl: _customBaseUrlCtrl.text.trim(),
        temperature: double.tryParse(_customTempCtrl.text.trim()) ?? 0.2,
        maxTokens: int.tryParse(_customMaxTokensCtrl.text.trim()) ?? 0,
        maxToolOutputSize:
            int.tryParse(_customMaxToolOutputSizeCtrl.text.trim()) ?? 2560000,
        tokenWarningThreshold:
            int.tryParse(_customTokenWarningThresholdCtrl.text.trim()) ??
            1500000,
        topK: int.tryParse(_customTopKCtrl.text.trim()),
        topP: double.tryParse(_customTopPCtrl.text.trim()),
        repeatPenalty: double.tryParse(_customRepeatPenaltyCtrl.text.trim()),
        seed: int.tryParse(_customSeedCtrl.text.trim()),
        thinking: _customThinking,
        isSlm: _customIsSlm,
        isMultiModal: _customIsMultiModal,
        useNativeToolCall: _customUseNativeTool,
        useStreaming: _customUseStreaming,
      );
    }
    return _controller.llmConfig;
  }

  void _syncCustomLlmInputs(LlmConfig config) {
    _customProvider = config.provider;
    _customModelCtrl.text = config.model;
    _customApiKeyCtrl.text = config.apiKey;
    _customBaseUrlCtrl.text = config.baseUrl;
    _customTempCtrl.text = config.temperature.toString();
    _customMaxTokensCtrl.text = config.maxTokens.toString();
    _customMaxToolOutputSizeCtrl.text = config.maxToolOutputSize.toString();
    _customTokenWarningThresholdCtrl.text =
        config.tokenWarningThreshold.toString();
    _customTopKCtrl.text = config.topK?.toString() ?? '';
    _customTopPCtrl.text = config.topP?.toString() ?? '';
    _customRepeatPenaltyCtrl.text = config.repeatPenalty?.toString() ?? '';
    _customSeedCtrl.text = config.seed?.toString() ?? '';
    _customThinking = config.thinking;
    _customIsSlm = config.isSlm;
    _customIsMultiModal = config.isMultiModal;
    _customUseNativeTool = config.useNativeToolCall;
    _customUseStreaming = config.useStreaming;
  }

  List<_ToolsetGroup> _getToolsetGroups() {
    final groups = <_ToolsetGroup>[];

    final weatherTools = _controller.localTools
        .where(
          (t) =>
              t.name == 'get_weather_forecast' ||
              t.name == 'get_current_weather' ||
              t.name == 'get_hourly_forecast' ||
              t.name == 'get_daily_forecast' ||
              t.name == 'geocode_weather_city',
        )
        .map((t) => t.toMCPTool())
        .toList();
    if (weatherTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Weather API',
          description:
              'Current, hourly, and daily forecasts, plus city geocoding via Open-Meteo.',
          tools: weatherTools,
        ),
      );
    }

    final interactiveChartTools = _controller.localTools
        .where((t) => t.name == 'create_chart_png')
        .map((t) => t.toMCPTool())
        .toList();
    if (interactiveChartTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Chart generator (Interactive)',
          description:
              'Generate interactive JSON charts rendered via fl_chart.',
          tools: interactiveChartTools,
        ),
      );
    }

    final imageChartTools = _controller.localTools
        .where((t) => t.name == 'chart2png')
        .map((t) => t.toMCPTool())
        .toList();
    if (imageChartTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Chart generator (PNG Image)',
          description: 'Generate flat PNG image charts from canvas rendering.',
          tools: imageChartTools,
        ),
      );
    }

    final sshTools = _controller.localTools
        .where(
          (t) =>
              t.name.startsWith('ssh_') ||
              t.name.startsWith('sftp_') ||
              t.name == 'ssh_execute_command',
        )
        .map((t) => t.toMCPTool())
        .toList();
    if (sshTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'SSH/SFTP',
          description:
              'Execute remote commands, list directories, read, and transfer files via SSH/SFTP.',
          tools: sshTools,
        ),
      );
    }

    final otherTools = _controller.localTools
        .where(
          (t) =>
              t.name != 'get_weather_forecast' &&
              t.name != 'get_current_weather' &&
              t.name != 'get_hourly_forecast' &&
              t.name != 'get_daily_forecast' &&
              t.name != 'geocode_weather_city' &&
              t.name != 'create_chart_png' &&
              t.name != 'chart2png' &&
              !t.name.startsWith('ssh_') &&
              !t.name.startsWith('sftp_'),
        )
        .map((t) => t.toMCPTool())
        .toList();
    if (otherTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Custom Local Tools',
          description:
              'Dart-native tools registered specifically in this playground instance.',
          tools: otherTools,
        ),
      );
    }

    for (final client in _controller.mcpClients) {
      final isExt = client.url.startsWith('http');
      groups.add(
        _ToolsetGroup(
          name: client.label,
          description: client.url,
          tools: client.availableTools,
          isExternal: isExt,
          isInstalled: !isExt,
        ),
      );
    }

    return groups;
  }

  bool _isToolsetEnabled(_ToolsetGroup group) {
    if (group.tools.isEmpty) return false;
    final enabled = _controller.enabledToolNames;
    return group.tools.every((t) => enabled.contains(t.name));
  }

  void _toggleToolsetGroup(_ToolsetGroup group, bool enable) {
    final updated = Set<String>.from(_controller.enabledToolNames);
    for (final t in group.tools) {
      if (enable) {
        updated.add(t.name);
      } else {
        updated.remove(t.name);
      }
    }
    _controller.updateEnabledTools(updated);
  }

  Future<void> _startPlayground() async {
    final activeLlm = _getActiveLlmConfig();
    if (!activeLlm.isConfigured && !widget.disableConfigDialog) {
      _showSettingsDialog();
      return;
    }

    setState(() {
      _playgroundStarted = true;
      _controller.systemPrompt = _systemPromptCtrl.text.trim();

      _genuiController?.dispose();
      _genuiController = McpGenuiChatController(
        llmConfig: activeLlm,
        tools: _controller.localTools,
        systemPrompt: _systemPromptCtrl.text.isNotEmpty
            ? _systemPromptCtrl.text
            : null,
        catalog: widget.genuiCatalog,
        catalogJson: widget.genuiCatalogJson,
        catalogItems: widget.genuiCatalogItems,
        playgroundController: _controller,
      );
      _genuiController!.addListener(_onStateChange);
    });

    if (_initialPromptCtrl.text.isNotEmpty) {
      final prompt = _initialPromptCtrl.text;
      _inputCtrl.text = prompt;
      _handleSend();
    }
  }

  void _resetPlayground() {
    _genuiController?.dispose();
    _genuiController = null;
    setState(() {
      _playgroundStarted = false;
      _controller.clearChat();
      _attachments.clear();
    });
  }

  Future<void> _handleSend() async {
    final text = _inputCtrl.text.trim();
    if (text.isEmpty && _attachments.isEmpty) return;

    if (_genuiController == null) {
      _startPlayground();
      return;
    }

    if (_genuiController!.isGenerating) return;

    _inputCtrl.clear();
    _attachments.clear();

    _genuiController!.sendMessage(text);
  }

  Future<void> _pickAttachments() async {
    try {
      final result = await FilePicker.pickFiles(
        allowMultiple: true,
        withData: true,
      );

      if (result != null && result.files.isNotEmpty) {
        setState(() {
          for (final file in result.files) {
            if (file.bytes != null) {
              final name = file.name;
              final mime = _mimeFromExtension(name);
              _attachments.add(
                MessageAttachment(
                  id: const Uuid().v4(),
                  name: name,
                  path: file.path ?? '',
                  bytes: file.bytes,
                  mimeType: mime,
                  size: file.size,
                ),
              );
            }
          }
        });
      }
    } catch (e) {
      debugPrint('Error picking files: $e');
    }
  }

  void _showSettingsDialog() {
    showDialog(
      context: context,
      builder: (ctx) => Dialog(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 800, maxHeight: 700),
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: SettingsDrawer(
              controller: _controller,
            ),
          ),
        ),
      ),
    );
  }

  void _showAgentInspectorDialog() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => DraggableScrollableSheet(
        initialChildSize: 0.85,
        minChildSize: 0.5,
        maxChildSize: 0.95,
        builder: (_, scrollCtrl) => Container(
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.surface,
            borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
          ),
          child: AgentInspector(
            controller: _controller,
          ),
        ),
      ),
    );
  }

  void _showSaveSkillDialog() {
    showDialog(
      context: context,
      builder: (ctx) => SkillSaveDialog(
        controller: _controller,
        unsentInput: _inputCtrl.text.trim().isNotEmpty
            ? _inputCtrl.text.trim()
            : null,
      ),
    );
  }

  Future<void> _showLoadSkillDialog() async {
    final result = await showDialog<SavedPlaygroundSetup>(
      context: context,
      builder: (ctx) => SkillLoadDialog(controller: _controller),
    );

    if (result == null || !mounted) return;

    setState(() {
      _loadedSetupId = result.id;
      _systemPromptCtrl.text = result.systemPrompt;
      _initialPromptCtrl.text = result.initialPrompt;
      _useCustomLlm = result.useCustomLlm;

      if (result.customLlmConfig != null) {
        final custom = result.customLlmConfig!;
        _syncCustomLlmInputs(custom);
      }

      _controller.updateEnabledTools(result.enabledToolNames.toSet());
    });
  }

  void _clearSetupInputs() {
    setState(() {
      _systemPromptCtrl.clear();
      _initialPromptCtrl.clear();
      _loadedSetupId = null;

      final allTools = _getToolsetGroups()
          .expand((g) => g.tools)
          .map((t) => t.name)
          .toSet();
      _controller.updateEnabledTools(allTools);
    });
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isWide = MediaQuery.sizeOf(context).width >= 900;

    final Widget bodyContent = _playgroundStarted
        ? _buildGenuiConversationView(theme)
        : _buildSetupView(theme);

    final loadedSetupName = _loadedSetupId != null
        ? _controller.savedSetups
            .cast<SavedPlaygroundSetup?>()
            .firstWhere((s) => s?.id == _loadedSetupId, orElse: () => null)
            ?.name
        : null;

    final l10n = _l10n;
    final bool showInspectorPane =
        isWide &&
        widget.showAgentInspector &&
        _inspectorVisible &&
        _playgroundStarted;

    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.menu),
          tooltip: l10n.get('menu'),
          onPressed: () => _scaffoldKey.currentState?.openDrawer(),
        ),
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: theme.colorScheme.primaryContainer,
                borderRadius: BorderRadius.circular(6),
              ),
              child: Text(
                'GenUI',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.bold,
                  color: theme.colorScheme.onPrimaryContainer,
                ),
              ),
            ),
            const SizedBox(width: 8),
            Text(
              loadedSetupName != null
                  ? '${l10n.get('playground')} - $loadedSetupName'
                  : l10n.get('playground'),
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
          ],
        ),
        actions: _buildAppBarActions(context),
      ),
      drawer: Drawer(
        child: ListView(
          padding: EdgeInsets.zero,
          children: [
            DrawerHeader(
              decoration: BoxDecoration(color: theme.colorScheme.primary),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  const Icon(
                    Icons.auto_awesome_rounded,
                    color: Colors.white,
                    size: 32,
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'GenUI ${l10n.get('agentPlayground')}',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ),
            ListTile(
              leading: const Icon(Icons.play_arrow),
              title: Text(l10n.get('playground')),
              onTap: () {
                Navigator.pop(context);
                _resetPlayground();
              },
            ),
            if (!widget.disableConfigDialog)
              ListTile(
                leading: const Icon(Icons.settings),
                title: Text(l10n.get('playgroundSettings')),
                onTap: () {
                  Navigator.pop(context);
                  _showSettingsDialog();
                },
              ),
          ],
        ),
      ),
      body: showInspectorPane
          ? LayoutBuilder(
              builder: (context, constraints) {
                final totalWidth = constraints.maxWidth;
                const minChatWidth = 300.0;
                const minInspectorWidth = 250.0;

                double chatWidth = totalWidth * _chatFraction;
                if (chatWidth < minChatWidth) {
                  chatWidth = minChatWidth;
                }
                if (totalWidth - chatWidth - 8 < minInspectorWidth) {
                  chatWidth = totalWidth - minInspectorWidth - 8;
                }

                return Row(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    SizedBox(width: chatWidth, child: bodyContent),
                    GestureDetector(
                      behavior: HitTestBehavior.translucent,
                      onHorizontalDragUpdate: (details) {
                        setState(() {
                          _chatFraction =
                              (chatWidth + details.delta.dx) / totalWidth;
                          if (_chatFraction < 0.2) _chatFraction = 0.2;
                          if (_chatFraction > 0.85) _chatFraction = 0.85;
                        });
                      },
                      child: MouseRegion(
                        cursor: SystemMouseCursors.resizeLeftRight,
                        child: Container(
                          width: 8,
                          color: theme.dividerColor.withValues(alpha: 0.1),
                          child: Center(
                            child: Container(
                              width: 1,
                              color: theme.dividerColor,
                            ),
                          ),
                        ),
                      ),
                    ),
                    Expanded(
                      child: AgentInspector(
                        controller: _controller,
                      ),
                    ),
                  ],
                );
              },
            )
          : bodyContent,
    );
  }

  List<Widget> _buildAppBarActions(BuildContext context) {
    final l10n = _l10n;
    final isWide = MediaQuery.sizeOf(context).width >= 900;

    return [
      if (_playgroundStarted && widget.showAgentInspector && isWide)
        IconButton(
          icon: Icon(
            _inspectorVisible
                ? Icons.view_sidebar_rounded
                : Icons.view_sidebar_outlined,
          ),
          tooltip: l10n.get('agentInspector'),
          onPressed: () {
            setState(() {
              _inspectorVisible = !_inspectorVisible;
            });
          },
        ),
      IconButton(
        icon: const Icon(Icons.refresh_rounded),
        tooltip: l10n.get('resetTooltip'),
        onPressed: _resetPlayground,
      ),
      PopupMenuButton<String>(
        icon: const Icon(Icons.more_vert),
        tooltip: l10n.get('moreActions'),
        onSelected: (val) {
          if (val == 'clear') {
            _clearSetupInputs();
          } else if (val == 'saveSkill') {
            _showSaveSkillDialog();
          } else if (val == 'loadSkill') {
            _showLoadSkillDialog();
          } else if (val == 'catalog') {
            RegisteredToolsDialog.show(context, _controller);
          } else if (val == 'inspector') {
            _showAgentInspectorDialog();
          }
        },
        itemBuilder: (ctx) => [
          if (!_playgroundStarted) ...[
            PopupMenuItem(
              value: 'clear',
              child: Row(
                children: [
                  const Icon(Icons.delete_sweep_outlined, size: 20),
                  const SizedBox(width: 12),
                  Text(l10n.get('clearTooltip')),
                ],
              ),
            ),
            const PopupMenuItem(
              value: 'loadSkill',
              child: Row(
                children: [
                  Icon(Icons.bookmarks_outlined, size: 20),
                  SizedBox(width: 12),
                  Text('Load Skill'),
                ],
              ),
            ),
          ],
          const PopupMenuItem(
            value: 'saveSkill',
            child: Row(
              children: [
                Icon(Icons.save_outlined, size: 20),
                SizedBox(width: 12),
                Text('Save Skill'),
              ],
            ),
          ),
          PopupMenuItem(
            value: 'catalog',
            child: Row(
              children: [
                const Icon(Icons.list_alt, size: 20),
                const SizedBox(width: 12),
                Text(l10n.get('catalogTooltip')),
              ],
            ),
          ),
          if (_playgroundStarted && widget.showAgentInspector)
            PopupMenuItem(
              value: 'inspector',
              child: Row(
                children: [
                  const Icon(Icons.analytics_outlined, size: 20),
                  const SizedBox(width: 12),
                  Text(l10n.get('agentInspector')),
                ],
              ),
            ),
        ],
      ),
    ];
  }

  Widget _buildSetupView(ThemeData theme) {
    return ListView(
      padding: const EdgeInsets.all(24.0),
      children: [
        Card(
          elevation: 0,
          color: theme.colorScheme.surfaceContainerLowest,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
            side: BorderSide(color: theme.dividerColor),
          ),
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Icon(
                      Icons.tune_rounded,
                      color: theme.colorScheme.primary,
                      size: 20,
                    ),
                    const SizedBox(width: 8),
                    Text(
                      'System Prompt & Instructions',
                      style: theme.textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: _systemPromptCtrl,
                  maxLines: 4,
                  decoration: InputDecoration(
                    hintText:
                        'Optional system prompt defining the GenUI agent role, behavior, and catalog instructions...',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                    contentPadding: const EdgeInsets.all(12),
                  ),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(height: 16),

        Card(
          elevation: 0,
          color: theme.colorScheme.surfaceContainerLowest,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
            side: BorderSide(color: theme.dividerColor),
          ),
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Icon(
                      Icons.build_circle_outlined,
                      color: theme.colorScheme.primary,
                      size: 20,
                    ),
                    const SizedBox(width: 8),
                    Text(
                      'Enabled Toolsets & MCP Tools',
                      style: theme.textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                ..._getToolsetGroups().map((group) {
                  final isEnabled = _isToolsetEnabled(group);
                  return CheckboxListTile(
                    title: Text(group.name),
                    subtitle: Text(group.description),
                    value: isEnabled,
                    onChanged: (val) {
                      _toggleToolsetGroup(group, val ?? false);
                    },
                    controlAffinity: ListTileControlAffinity.leading,
                    contentPadding: EdgeInsets.zero,
                  );
                }),
              ],
            ),
          ),
        ),
        const SizedBox(height: 24),

        SizedBox(
          width: double.infinity,
          height: 48,
          child: FilledButton.icon(
            icon: const Icon(Icons.play_arrow_rounded),
            label: const Text(
              'Start GenUI Agent Playground',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
            ),
            onPressed: _startPlayground,
          ),
        ),
      ],
    );
  }

  Widget _buildGenuiConversationView(ThemeData theme) {
    if (_genuiController == null) {
      return const Center(child: CircularProgressIndicator());
    }

    final isGenerating = _genuiController!.isGenerating;

    return Column(
      children: [
        Expanded(
          child: AnimatedBuilder(
            animation: _genuiController!,
            builder: (context, _) {
              final entries = _genuiController!.entries;
              if (entries.isEmpty) {
                return _buildWelcomeWidget(theme);
              }
              return ListView(
                controller: _scrollCtrl,
                padding: const EdgeInsets.only(bottom: 24),
                children: [
                  for (final entry in entries)
                    _buildGenuiEntry(context, entry, theme),
                ],
              );
            },
          ),
        ),
        if (isGenerating)
          Padding(
            padding: const EdgeInsets.symmetric(
              vertical: 8.0,
              horizontal: 16.0,
            ),
            child: Row(
              children: [
                const SizedBox(
                  width: 14,
                  height: 14,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
                const SizedBox(width: 8),
                Text(
                  'GenUI Agent is generating interactive widgets and tool calls...',
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: Colors.grey,
                  ),
                ),
              ],
            ),
          ),
        _buildInputBar(theme),
      ],
    );
  }

  Widget _buildGenuiEntry(
    BuildContext context,
    GenuiChatEntry entry,
    ThemeData theme,
  ) {
    final isDark = theme.brightness == Brightness.dark;

    switch (entry.kind) {
      case GenuiChatEntryKind.user:
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 16),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              Flexible(
                child: Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: theme.colorScheme.primary.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Text(entry.text),
                ),
              ),
            ],
          ),
        );
      case GenuiChatEntryKind.assistant:
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 16),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              CircleAvatar(
                radius: 14,
                backgroundColor: isDark
                    ? Colors.white.withValues(alpha: 0.1)
                    : theme.colorScheme.primaryContainer,
                child: Icon(
                  Icons.auto_awesome_rounded,
                  size: 16,
                  color: isDark
                      ? Colors.white
                      : theme.colorScheme.onPrimaryContainer,
                ),
              ),
              const SizedBox(width: 8),
              Flexible(
                child: Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isDark
                        ? Colors.white.withValues(alpha: 0.05)
                        : Colors.black.withValues(alpha: 0.04),
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Text(entry.text),
                ),
              ),
            ],
          ),
        );
      case GenuiChatEntryKind.surface:
        if (entry.surfaceId != null) {
          return Card(
            margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
            elevation: 2,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Surface(
                surfaceContext: _genuiController!.contextFor(entry.surfaceId!),
              ),
            ),
          );
        }
        return const SizedBox.shrink();
      case GenuiChatEntryKind.error:
        return Container(
          margin: const EdgeInsets.symmetric(vertical: 6, horizontal: 16),
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: theme.colorScheme.errorContainer.withValues(alpha: 0.4),
            borderRadius: BorderRadius.circular(12),
          ),
          child: Text(
            entry.text,
            style: TextStyle(
              color: theme.colorScheme.onErrorContainer,
              fontFamily: 'monospace',
              fontSize: 12,
            ),
          ),
        );
    }
  }

  Widget _buildWelcomeWidget(ThemeData theme) {
    return Center(
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(
                Icons.auto_awesome_rounded,
                size: 72,
                color: theme.colorScheme.primary.withValues(alpha: 0.5),
              ),
              const SizedBox(height: 16),
              Text(
                'GenUI Playground Ready',
                style: theme.textTheme.titleLarge?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Interactive GenUI widgets will be dynamically rendered directly from agent responses and MCP tool calls.',
                textAlign: TextAlign.center,
                style: theme.textTheme.bodyMedium?.copyWith(color: Colors.grey),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildAttachmentPreviews() {
    if (_attachments.isEmpty) return const SizedBox.shrink();
    return Container(
      height: 50,
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: _attachments.length,
        itemBuilder: (ctx, idx) {
          final att = _attachments[idx];
          return Container(
            margin: const EdgeInsets.only(right: 8),
            child: InputChip(
              label: Text(att.name, style: const TextStyle(fontSize: 11)),
              onDeleted: () {
                setState(() {
                  _attachments.removeAt(idx);
                });
              },
            ),
          );
        },
      ),
    );
  }

  Widget _buildInputBar(ThemeData theme) {
    final isGen = _genuiController?.isGenerating ?? false;
    final showButton =
        _inputCtrl.text.isNotEmpty || _attachments.isNotEmpty || !isGen;

    return Container(
      decoration: BoxDecoration(
        color: theme.colorScheme.surface,
        border: Border(top: BorderSide(color: theme.dividerColor)),
      ),
      child: SafeArea(
        top: false,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              _buildAttachmentPreviews(),
              SubPromptListEditor(
                controller: _inputCtrl,
                chatMode: _chatMode,
                availableToolGroups: _getToolsetGroups()
                    .where((g) => _isToolsetEnabled(g))
                    .map(
                      (g) => ToolGroup(
                        name: g.name,
                        toolNames: g.tools.map((t) => t.name).toList(),
                      ),
                    )
                    .toList(),
                minLines: 1,
                maxLines: 6,
                hintText: isGen
                    ? 'GenUI Agent is working...'
                    : 'Ask the GenUI agent to render UI or run tools...',
              ),
              const SizedBox(height: 8),
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.attach_file_outlined),
                    tooltip: 'Attach Files / Images',
                    onPressed: isGen ? null : _pickAttachments,
                  ),
                  const Spacer(),
                  if (isGen)
                    const Padding(
                      padding: EdgeInsets.symmetric(horizontal: 12.0),
                      child: SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(strokeWidth: 2.5),
                      ),
                    )
                  else
                    IconButton(
                      icon: Icon(
                        Icons.send_rounded,
                        color: showButton &&
                                _controller.activeLlmConfig.isConfigured
                            ? theme.colorScheme.primary
                            : Colors.grey,
                      ),
                      onPressed: showButton &&
                              _controller.activeLlmConfig.isConfigured
                          ? _handleSend
                          : null,
                    ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _ToolsetGroup {
  final String name;
  final String description;
  final List<MCPTool> tools;
  final bool isExternal;
  final bool isInstalled;

  _ToolsetGroup({
    required this.name,
    required this.description,
    required this.tools,
    this.isExternal = false,
    this.isInstalled = false,
  });
}
