import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:genui/genui.dart' hide ChatMessage;
import 'package:mcp_playground_dart/mcp_playground_dart.dart' hide LocalMCPClient;
import 'package:mcp_playground_ui/mcp_playground_ui.dart';
import 'package:uuid/uuid.dart';

import 'genui_catalog.dart';
import 'genui_chat_controller.dart';

String _mimeFromExtension(String name) => mimeFromExtension(name);

/// An interactive GenUI AI Agent Playground widget for Flutter.
///
/// Connects to various LLM providers, registers Dart-native tools,
/// remote HTTP/S MCP servers, local MCP subprocesses, and dynamically renders
/// interactive Flutter widgets generated by the model.
class GenuiMcpPlayground extends StatefulWidget {
  /// Default LLM setup parameters.
  final LlmConfig? initialLlmConfig;

  /// Default list of HTTP/HTTPS MCP servers to connect to.
  final List<McpServerConfig>? initialServers;

  /// Optional list of local MCP servers to auto-initialize/install.
  final List<LocalMcpServerSetup>? initialLocalMcpServers;

  /// Optional delegate to customize settings save/load operations.
  final McpPlaygroundStorageDelegate? storageDelegate;

  /// Custom list of internal, Dart-native tools to register.
  final List<McpLocalTool>? customLocalTools;

  /// Whether to disable opening the configuration dialog when LLM is not configured.
  final bool disableConfigDialog;

  /// Optional locale override ('en' or 'de').
  final String? locale;

  /// Whether to print clean console logs for key events.
  final bool enableLogging;

  /// Optional list of GenUI catalog items to register.
  final List<GenuiCatalogItemDefinition>? genuiCatalogItems;

  /// Optional custom GenUI catalog.
  final Catalog? genuiCatalog;

  /// Optional catalog JSON string.
  final String? genuiCatalogJson;

  /// Optional list of GenUI client-side functions to register into the catalog.
  final List<ClientFunction>? clientFunctions;

  /// Whether to show the Agent Inspector side panel and toggle button. Defaults to true.
  final bool showAgentInspector;

  /// Optional initial system prompt.
  final String? initialSystemPrompt;

  /// Optional list of tool names to pre-select as active on startup.
  final List<String>? initialEnabledTools;

  /// Creates a new [GenuiMcpPlayground] widget instance.
  const GenuiMcpPlayground({
    super.key,
    this.initialLlmConfig,
    this.initialServers,
    this.initialLocalMcpServers,
    this.storageDelegate,
    this.customLocalTools,
    this.disableConfigDialog = false,
    this.locale,
    this.enableLogging = false,
    this.genuiCatalogItems,
    this.genuiCatalog,
    this.genuiCatalogJson,
    this.clientFunctions,
    this.showAgentInspector = true,
    this.initialSystemPrompt,
    this.initialEnabledTools,
  });

  @override
  State<GenuiMcpPlayground> createState() => _GenuiMcpPlaygroundState();
}

class _GenuiMcpPlaygroundState extends State<GenuiMcpPlayground> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  final _inputCtrl = TextEditingController();
  final _scrollCtrl = ScrollController();
  final List<MessageAttachment> _attachments = [];

  late PlaygroundController _controller;
  late McpPlaygroundLocalizations _l10n;

  bool _playgroundStarted = false;
  double _chatFraction = 0.7;
  bool _inspectorVisible = true;
  McpGenuiChatController? _genuiController;

  // Setup form states
  final _systemPromptCtrl = TextEditingController();
  final _initialPromptCtrl = TextEditingController();
  bool _chatMode = false;
  bool _isGeneratingSystemPrompt = false;

  // Custom LLM Override state
  bool _useCustomLlm = false;
  LlmProvider _customProvider = LlmProvider.none;
  final _customModelCtrl = TextEditingController();
  final _customApiKeyCtrl = TextEditingController();
  final _customBaseUrlCtrl = TextEditingController();

  final Map<LlmProvider, _CustomProviderCache> _customProviderCache = {};

  final _customTempCtrl = TextEditingController(text: '0.2');
  final _customMaxTokensCtrl = TextEditingController(text: '0');
  final _customMaxToolOutputSizeCtrl = TextEditingController(text: '2560000');
  final _customTokenWarningThresholdCtrl = TextEditingController(
    text: '1500000',
  );
  final _customTopKCtrl = TextEditingController();
  final _customTopPCtrl = TextEditingController();
  final _customRepeatPenaltyCtrl = TextEditingController();
  final _customSeedCtrl = TextEditingController();
  bool _customThinking = false;
  bool _customIsSlm = false;
  bool _customIsMultiModal = true;
  bool _customUseNativeTool = true;
  bool _customUseStreaming = false;

  @override
  void initState() {
    super.initState();
    if (widget.initialSystemPrompt != null) {
      _systemPromptCtrl.text = widget.initialSystemPrompt!;
    }
    _controller = PlaygroundController(
      initialLlmConfig: widget.initialLlmConfig,
      initialServers: widget.initialServers,
      customLocalTools: widget.customLocalTools,
      storageDelegate: widget.storageDelegate,
      enableLogging: widget.enableLogging,
    );
    _controller.addListener(_onStateChange);

    WidgetsBinding.instance.addPostFrameCallback((_) async {
      if (widget.initialEnabledTools != null) {
        _controller.updateEnabledTools(widget.initialEnabledTools!.toSet());
      }
      await _checkAndInstallInitialLocalMcpServers();
    });
  }

  void _onStateChange() {
    if (mounted) {
      setState(() {});
      if (_controller.messages.isNotEmpty ||
          (_genuiController?.entries.isNotEmpty ?? false)) {
        Future.delayed(const Duration(milliseconds: 100), _scrollToBottom);
      }
    }
  }

  Future<void> _checkAndInstallInitialLocalMcpServers() async {
    final isDesktop =
        !kIsWeb &&
        (defaultTargetPlatform == TargetPlatform.windows ||
            defaultTargetPlatform == TargetPlatform.linux ||
            defaultTargetPlatform == TargetPlatform.macOS);
    if (!isDesktop) return;

    while (_controller.isLoading && mounted) {
      await Future.delayed(const Duration(milliseconds: 100));
    }
    if (!mounted) return;

    final localServersSetup = widget.initialLocalMcpServers;
    if (localServersSetup == null || localServersSetup.isEmpty) return;

    final List<LocalMcpServerSetup> serversToInstall = [];
    final List<McpServerConfig> configsToRegister = [];

    for (final setup in localServersSetup) {
      final existingIdx = _controller.servers.indexWhere(
        (s) => s.name == setup.name,
      );

      McpServerConfig? config;
      bool needsInstall = false;

      if (existingIdx != -1) {
        config = _controller.servers[existingIdx];
        if (setup.reinstall || !config.isInstalled) {
          needsInstall = true;
        }
      } else {
        needsInstall = true;
        config = McpServerConfig(
          id: const Uuid().v4(),
          name: setup.name,
          url: setup.launchArguments ?? '',
          isLocal: true,
          localType: setup.type,
          localInstallMethod: setup.method,
          localPackage: setup.packageOrServerName,
          localCommand: setup.installCommand,
          customLaunchCommand: setup.launchCommand,
          localEnvVars: setup.envVars,
          isInstalled: false,
          enabled: true,
        );
        configsToRegister.add(config);
      }

      if (needsInstall) {
        serversToInstall.add(setup);
      }
    }

    for (final config in configsToRegister) {
      await _controller.addServer(config, autoSelectTools: false);
    }

    if (serversToInstall.isEmpty || !mounted) return;

    await showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => InitialMcpInstallProgressDialog(
        serversToInstall: serversToInstall,
        controller: _controller,
      ),
    );
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _l10n = McpPlaygroundLocalizations.of(
      context,
      overrideLocale: widget.locale,
    );
  }

  @override
  void dispose() {
    _controller.removeListener(_onStateChange);
    _controller.dispose();
    _genuiController?.dispose();
    _inputCtrl.dispose();
    _scrollCtrl.dispose();
    _systemPromptCtrl.dispose();
    _initialPromptCtrl.dispose();
    _customModelCtrl.dispose();
    _customApiKeyCtrl.dispose();
    _customBaseUrlCtrl.dispose();
    _customTempCtrl.dispose();
    _customMaxTokensCtrl.dispose();
    _customMaxToolOutputSizeCtrl.dispose();
    _customTokenWarningThresholdCtrl.dispose();
    _customTopKCtrl.dispose();
    _customTopPCtrl.dispose();
    _customRepeatPenaltyCtrl.dispose();
    _customSeedCtrl.dispose();
    super.dispose();
  }

  void _scrollToBottom() {
    if (_scrollCtrl.hasClients) {
      _scrollCtrl.animateTo(
        _scrollCtrl.position.maxScrollExtent,
        duration: const Duration(milliseconds: 250),
        curve: Curves.easeOut,
      );
    }
  }

  LlmConfig _getActiveLlmConfig() {
    if (_useCustomLlm) {
      return LlmConfig(
        provider: _customProvider,
        model: _customModelCtrl.text.trim(),
        apiKey: _customApiKeyCtrl.text.trim(),
        baseUrl: _customBaseUrlCtrl.text.trim(),
        temperature: double.tryParse(_customTempCtrl.text.trim()) ?? 0.2,
        maxTokens: int.tryParse(_customMaxTokensCtrl.text.trim()) ?? 0,
        maxToolOutputSize:
            int.tryParse(_customMaxToolOutputSizeCtrl.text.trim()) ?? 2560000,
        tokenWarningThreshold:
            int.tryParse(_customTokenWarningThresholdCtrl.text.trim()) ??
            1500000,
        topK: int.tryParse(_customTopKCtrl.text.trim()),
        topP: double.tryParse(_customTopPCtrl.text.trim()),
        repeatPenalty: double.tryParse(_customRepeatPenaltyCtrl.text.trim()),
        seed: int.tryParse(_customSeedCtrl.text.trim()),
        thinking: _customThinking,
        isSlm: _customIsSlm,
        isMultiModal: _customIsMultiModal,
        useNativeToolCall: _customUseNativeTool,
        useStreaming: _customUseStreaming,
      );
    }
    return _controller.llmConfig;
  }

  void _syncCustomLlmInputs(LlmConfig config) {
    _customProvider = config.provider;
    _customModelCtrl.text = config.model;
    _customApiKeyCtrl.text = config.apiKey;
    _customBaseUrlCtrl.text = config.baseUrl;
    _customTempCtrl.text = config.temperature.toString();
    _customMaxTokensCtrl.text = config.maxTokens.toString();
    _customMaxToolOutputSizeCtrl.text = config.maxToolOutputSize.toString();
    _customTokenWarningThresholdCtrl.text =
        config.tokenWarningThreshold.toString();
    _customTopKCtrl.text = config.topK?.toString() ?? '';
    _customTopPCtrl.text = config.topP?.toString() ?? '';
    _customRepeatPenaltyCtrl.text = config.repeatPenalty?.toString() ?? '';
    _customSeedCtrl.text = config.seed?.toString() ?? '';
    _customThinking = config.thinking;
    _customIsSlm = config.isSlm;
    _customIsMultiModal = config.isMultiModal;
    _customUseNativeTool = config.useNativeToolCall;
    _customUseStreaming = config.useStreaming;
  }

  List<_ToolsetGroup> _getToolsetGroups() {
    final groups = <_ToolsetGroup>[];

    final weatherTools = _controller.localTools
        .where(
          (t) =>
              t.name == 'get_weather_forecast' ||
              t.name == 'get_current_weather' ||
              t.name == 'get_hourly_forecast' ||
              t.name == 'get_daily_forecast' ||
              t.name == 'geocode_weather_city',
        )
        .map((t) => t.toMCPTool())
        .toList();
    if (weatherTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Weather API',
          description:
              'Current, hourly, and daily forecasts, plus city geocoding via Open-Meteo.',
          tools: weatherTools,
        ),
      );
    }

    final interactiveChartTools = _controller.localTools
        .where((t) => t.name == 'create_chart_png')
        .map((t) => t.toMCPTool())
        .toList();
    if (interactiveChartTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Chart generator (Interactive)',
          description:
              'Generate interactive JSON charts rendered via fl_chart.',
          tools: interactiveChartTools,
        ),
      );
    }

    final imageChartTools = _controller.localTools
        .where((t) => t.name == 'chart2png')
        .map((t) => t.toMCPTool())
        .toList();
    if (imageChartTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Chart generator (PNG Image)',
          description: 'Generate flat PNG image charts from canvas rendering.',
          tools: imageChartTools,
        ),
      );
    }

    final sshTools = _controller.localTools
        .where(
          (t) =>
              t.name.startsWith('ssh_') ||
              t.name.startsWith('sftp_') ||
              t.name == 'ssh_execute_command',
        )
        .map((t) => t.toMCPTool())
        .toList();
    if (sshTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'SSH/SFTP',
          description:
              'Execute remote commands, list directories, read, and transfer files via SSH/SFTP.',
          tools: sshTools,
        ),
      );
    }

    final otherTools = _controller.localTools
        .where(
          (t) =>
              t.name != 'get_weather_forecast' &&
              t.name != 'get_current_weather' &&
              t.name != 'get_hourly_forecast' &&
              t.name != 'get_daily_forecast' &&
              t.name != 'geocode_weather_city' &&
              t.name != 'create_chart_png' &&
              t.name != 'chart2png' &&
              !t.name.startsWith('ssh_') &&
              !t.name.startsWith('sftp_'),
        )
        .map((t) => t.toMCPTool())
        .toList();
    if (otherTools.isNotEmpty) {
      groups.add(
        _ToolsetGroup(
          name: 'Custom Local Tools',
          description:
              'Dart-native tools registered specifically in this playground instance.',
          tools: otherTools,
        ),
      );
    }

    for (final client in _controller.mcpClients) {
      final isExt = client.url.startsWith('http');
      groups.add(
        _ToolsetGroup(
          name: client.label,
          description: client.url,
          tools: client.availableTools,
          isExternal: isExt,
          isInstalled: !isExt,
        ),
      );
    }

    return groups;
  }

  bool _isToolsetEnabled(_ToolsetGroup group) {
    if (group.tools.isEmpty) return false;
    final enabled = _controller.enabledToolNames;
    return group.tools.every((t) => enabled.contains(t.name));
  }

  void _toggleToolsetGroup(_ToolsetGroup group, bool enable) {
    final updated = Set<String>.from(_controller.enabledToolNames);
    for (final t in group.tools) {
      if (enable) {
        updated.add(t.name);
      } else {
        updated.remove(t.name);
      }
    }
    _controller.updateEnabledTools(updated);
  }

  Future<void> _startPlayground() async {
    final activeLlm = _getActiveLlmConfig();
    if (!activeLlm.isConfigured && !widget.disableConfigDialog) {
      _showSettingsDialog();
      return;
    }

    setState(() {
      _playgroundStarted = true;
      _controller.systemPrompt = _systemPromptCtrl.text.trim();

      _genuiController?.dispose();
      _genuiController = McpGenuiChatController(
        llmConfig: activeLlm,
        tools: _controller.localTools,
        systemPrompt: _systemPromptCtrl.text.isNotEmpty
            ? _systemPromptCtrl.text
            : null,
        catalog: widget.genuiCatalog,
        catalogJson: widget.genuiCatalogJson,
        catalogItems: widget.genuiCatalogItems,
        clientFunctions: widget.clientFunctions,
        playgroundController: _controller,
      );
      _genuiController!.addListener(_onStateChange);
    });

    if (_initialPromptCtrl.text.isNotEmpty) {
      final prompt = _initialPromptCtrl.text;
      _inputCtrl.text = prompt;
      _handleSend();
    }
  }

  void _resetPlayground() {
    _genuiController?.dispose();
    _genuiController = null;
    setState(() {
      _playgroundStarted = false;
      _controller.clearChat();
      _attachments.clear();
    });
  }

  Future<void> _handleSend() async {
    final text = _inputCtrl.text.trim();
    if (text.isEmpty && _attachments.isEmpty) return;

    if (_genuiController == null) {
      _startPlayground();
      return;
    }

    if (_genuiController!.isGenerating) return;

    final atts = List<MessageAttachment>.from(_attachments);
    _inputCtrl.clear();
    _attachments.clear();

    _genuiController!.sendMessage(text, attachments: atts);
  }

  Future<void> _pickAttachments() async {
    try {
      final files = await FilePicker.pickFiles();

      if (files.isNotEmpty) {
        for (final file in files) {
          final bytes = await file.readAsBytes();
          final name = file.name;
          final mime = _mimeFromExtension(name);
          final size = bytes.length;
          _attachments.add(
            MessageAttachment(
              id: const Uuid().v4(),
              name: name,
              path: file.path ?? '',
              bytes: bytes,
              mimeType: mime,
              size: size,
            ),
          );
        }
        setState(() {});
      }
    } catch (e) {
      debugPrint('Error picking files: $e');
    }
  }

  void _showSettingsDialog() {
    showDialog(
      context: context,
      builder: (ctx) => Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),
        child: SizedBox(
          width: 820,
          height: 720,
          child: ClipRRect(
            borderRadius: BorderRadius.circular(16),
            child: SettingsDrawer(
              controller: _controller,
            ),
          ),
        ),
      ),
    );
  }

  void _showAgentInspectorDialog() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => DraggableScrollableSheet(
        initialChildSize: 0.85,
        minChildSize: 0.5,
        maxChildSize: 0.95,
        builder: (_, scrollCtrl) => Container(
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.surface,
            borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
          ),
          child: AgentInspector(
            controller: _controller,
          ),
        ),
      ),
    );
  }

  void _showSaveWorkflowDialog() {
    showDialog(
      context: context,
      builder: (ctx) => WorkflowSaveDialog(
        controller: _controller,
        unsentInput: _inputCtrl.text.trim().isNotEmpty
            ? _inputCtrl.text.trim()
            : (_initialPromptCtrl.text.trim().isNotEmpty
                ? _initialPromptCtrl.text.trim()
                : null),
      ),
    );
  }

  Future<void> _showLoadWorkflowDialog() async {
    final result = await showDialog<PlaygroundWorkflow>(
      context: context,
      builder: (ctx) => WorkflowLoadDialog(controller: _controller),
    );

    if (result == null || !mounted) return;

    setState(() {
      _systemPromptCtrl.text = result.systemPrompt;
      _initialPromptCtrl.text = result.initialPrompt.isNotEmpty
          ? result.initialPrompt
          : result.steps.map((s) => s.text).join('\n++#++\n');
      _chatMode = result.chatMode;
      _useCustomLlm = result.useCustomLlm;

      if (result.customLlmConfig != null) {
        final custom = result.customLlmConfig!;
        _syncCustomLlmInputs(custom);
      }

      _controller.updateEnabledTools(result.enabledToolNames.toSet());

      if (result.activeSkillId != null) {
        final match = _controller.skills
            .where((s) => s.id == result.activeSkillId)
            .toList();
        if (match.isNotEmpty) {
          _controller.setActiveSkill(match.first);
        }
      }
    });
  }

  Future<void> _showSkillsManagerDialog() async {
    await SkillsManagerDialog.show(context, _controller);
  }

  Future<void> _showSkillWizardDialog() async {
    final result = await showDialog<SkillDef>(
      context: context,
      builder: (ctx) => SkillWizardDialog(controller: _controller),
    );
    if (result != null) {
      await _controller.saveSkill(result);
      _controller.setActiveSkill(result);
    }
  }

  void _showToolChecklistDialog() {
    final isMobileView = MediaQuery.of(context).size.width < 600;

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) {
        return ListenableBuilder(
          listenable: _controller,
          builder: (ctx2, _) {
            return StatefulBuilder(
              builder: (context, setDialogState) {
                final groups = _getToolsetGroups();
                final content = ListView(
                  shrinkWrap: true,
                  children: [
                    ...groups.map((group) {
                      final isEnabled = _isToolsetEnabled(group);
                      return CheckboxListTile(
                        title: Text(
                          group.name,
                          style: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 14,
                          ),
                        ),
                        subtitle: Text(
                          group.description,
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(fontSize: 12),
                        ),
                        value: isEnabled,
                        onChanged: (val) {
                          setDialogState(() {
                            _toggleToolsetGroup(group, val ?? false);
                          });
                        },
                      );
                    }),
                  ],
                );

                if (isMobileView) {
                  return Dialog.fullscreen(
                    child: Scaffold(
                      appBar: AppBar(
                        title: const Text('Select Tools'),
                        actions: [
                          IconButton(
                            icon: const Icon(Icons.check),
                            onPressed: () => Navigator.pop(ctx),
                          ),
                        ],
                      ),
                      body: content,
                    ),
                  );
                }

                return AlertDialog(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(20),
                  ),
                  title: const Text(
                    'Select Tools',
                    style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
                  ),
                  content: SizedBox(width: 480, child: content),
                  actions: [
                    FilledButton(
                      onPressed: () => Navigator.pop(ctx),
                      child: const Text('Done'),
                    ),
                  ],
                );
              },
            );
          },
        );
      },
    );
  }

  void _showIndividualToolsDialog(_ToolsetGroup group) {
    showDialog(
      context: context,
      builder: (ctx) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            final enabled = _controller.enabledToolNames;
            final sortedTools = List<MCPTool>.from(group.tools)
              ..sort((a, b) => a.name.compareTo(b.name));
            return AlertDialog(
              title: Text(
                'Select tools from ${group.name}',
                style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
              ),
              content: SizedBox(
                width: 400,
                child: ListView(
                  shrinkWrap: true,
                  children: sortedTools.map((t) {
                    final isEnabled = enabled.contains(t.name);
                    return CheckboxListTile(
                      dense: true,
                      title: Text(t.name, style: const TextStyle(fontSize: 13)),
                      subtitle: t.description != null && t.description!.isNotEmpty
                          ? Text(
                              t.description!,
                              maxLines: 2,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(fontSize: 11),
                            )
                          : null,
                      value: isEnabled,
                      onChanged: (val) {
                        setDialogState(() {
                          _controller.toggleToolEnabled(t.name, val ?? false);
                        });
                        setState(() {});
                      },
                    );
                  }).toList(),
                ),
              ),
              actions: [
                FilledButton(
                  onPressed: () => Navigator.pop(ctx),
                  child: const Text('Done'),
                ),
              ],
            );
          },
        );
      },
    );
  }

  void _showSelectedToolsDialog() {
    final groups = _getToolsetGroups();
    final enabled = _controller.enabledToolNames;
    final enabledTools = groups
        .expand((g) => g.tools)
        .where((t) => enabled.contains(t.name))
        .toList();

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Selected Tools'),
        content: SizedBox(
          width: 320,
          child: enabledTools.isEmpty
              ? const Text('No tools selected.')
              : ListView.builder(
                  shrinkWrap: true,
                  itemCount: enabledTools.length,
                  itemBuilder: (context, index) {
                    final tool = enabledTools[index];
                    return Material(
                      type: MaterialType.transparency,
                      child: ListTile(
                        dense: true,
                        leading: const Icon(Icons.build, size: 16),
                        title: Text(
                          tool.name,
                          style: const TextStyle(
                            fontFamily: 'monospace',
                            fontSize: 13,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        subtitle: tool.description != null &&
                                tool.description!.isNotEmpty
                            ? Text(
                                tool.description!,
                                maxLines: 2,
                                overflow: TextOverflow.ellipsis,
                              )
                            : null,
                      ),
                    );
                  },
                ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  void _applyLlmDefaults() {
    final def = _controller.llmConfig;
    if (def.provider != LlmProvider.none) {
      _customProvider = def.provider;
      _customModelCtrl.text = def.model;
      _customApiKeyCtrl.text = def.apiKey;
      _customBaseUrlCtrl.text = def.baseUrl;
      _customTempCtrl.text = def.temperature.toString();
      _customMaxTokensCtrl.text = def.maxTokens.toString();
      _customMaxToolOutputSizeCtrl.text = def.maxToolOutputSize.toString();
      _customTokenWarningThresholdCtrl.text =
          def.tokenWarningThreshold.toString();
      _customTopKCtrl.text = def.topK?.toString() ?? '';
      _customTopPCtrl.text = def.topP?.toString() ?? '';
      _customRepeatPenaltyCtrl.text = def.repeatPenalty?.toString() ?? '';
      _customSeedCtrl.text = def.seed?.toString() ?? '';
      _customThinking = def.thinking;
      _customIsSlm = def.isSlm;
      _customIsMultiModal = def.isMultiModal;
      _customUseNativeTool = def.useNativeToolCall;
      _customUseStreaming = def.useStreaming;
    }
  }

  Future<void> _generateSystemPrompt() async {
    final activeConfig = _getActiveLlmConfig();
    if (!activeConfig.isConfigured) return;

    setState(() {
      _isGeneratingSystemPrompt = true;
    });

    try {
      final groups = _getToolsetGroups();
      final enabledGroups = groups.where((g) => _isToolsetEnabled(g)).toList();

      String promptText =
          'Write a concise, professional system prompt (maximum 2-3 sentences) for a GenUI AI assistant. ';
      if (enabledGroups.isNotEmpty) {
        final toolDetails = enabledGroups
            .map((g) => '${g.name}: ${g.description}')
            .join('\n');
        promptText +=
            'The assistant is equipped with the following toolsets:\n$toolDetails\n\n';
        promptText +=
            'Focus on how the assistant should behave, be direct, and optimize usage of these tools. ';
      } else {
        promptText += 'Focus on being helpful, direct, and clear. ';
      }
      promptText +=
          'Respond ONLY with the generated system prompt text, with no introduction, quotes, or explanations.';

      final messages = [
        ChatMessage(
          id: const Uuid().v4(),
          content: promptText,
          role: ChatRole.user,
          timestamp: DateTime.now(),
        ),
      ];

      final response = await LLMService.generate(
        config: activeConfig,
        messages: messages,
        tools: const [],
        systemPrompt:
            'You are a prompt engineering expert. You output only the final requested prompt text with no markdown formatting or surrounding quotes.',
      );

      if (response.text.isNotEmpty && mounted) {
        setState(() {
          String text = response.text.trim();
          if (text.startsWith('"') && text.endsWith('"')) {
            text = text.substring(1, text.length - 1);
          }
          if (text.startsWith("'") && text.endsWith("'")) {
            text = text.substring(1, text.length - 1);
          }
          _systemPromptCtrl.text = text.trim();
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to generate system prompt: $e'),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isGeneratingSystemPrompt = false;
        });
      }
    }
  }

  void _clearSetupInputs() {
    setState(() {
      _systemPromptCtrl.clear();
      _initialPromptCtrl.clear();
      _controller.setLoadedWorkflowId(null);
      _chatMode = false;
      _controller.updateEnabledTools({});
    });
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isWide = MediaQuery.sizeOf(context).width >= 600;

    final Widget bodyContent = _playgroundStarted
        ? _buildGenuiConversationView(theme)
        : _buildSetupView(theme);

    final loadedWorkflow = _controller.loadedWorkflowId != null
        ? _controller.workflows
            .where((w) => w.id == _controller.loadedWorkflowId)
            .firstOrNull
        : null;

    final l10n = _l10n;
    final bool showInspectorPane =
        isWide &&
        widget.showAgentInspector &&
        _inspectorVisible &&
        _playgroundStarted;

    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.menu),
          tooltip: l10n.get('menu'),
          onPressed: () => _scaffoldKey.currentState?.openDrawer(),
        ),
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: theme.colorScheme.primaryContainer,
                borderRadius: BorderRadius.circular(6),
              ),
              child: Text(
                'GenUI',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.bold,
                  color: theme.colorScheme.onPrimaryContainer,
                ),
              ),
            ),
            const SizedBox(width: 8),
            Text(
              loadedWorkflow != null
                  ? '${l10n.get('playground')} - ${loadedWorkflow.name}'
                  : l10n.get('playground'),
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
          ],
        ),
        actions: _buildAppBarActions(context),
      ),
      drawer: Drawer(
        child: ListView(
          padding: EdgeInsets.zero,
          children: [
            DrawerHeader(
              decoration: BoxDecoration(color: theme.colorScheme.primary),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  const Icon(
                    Icons.auto_awesome_rounded,
                    color: Colors.white,
                    size: 32,
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'GenUI ${l10n.get('agentPlayground')}',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ),
            Material(
              type: MaterialType.transparency,
              child: ListTile(
                leading: const Icon(Icons.play_arrow),
                title: Text(l10n.get('playground')),
                onTap: () {
                  Navigator.pop(context);
                  _resetPlayground();
                },
              ),
            ),
            if (!widget.disableConfigDialog)
              Material(
                type: MaterialType.transparency,
                child: ListTile(
                  leading: const Icon(Icons.settings),
                  title: Text(l10n.get('playgroundSettings')),
                  onTap: () {
                    Navigator.pop(context);
                    _showSettingsDialog();
                  },
                ),
              ),
          ],
        ),
      ),
      body: showInspectorPane
          ? LayoutBuilder(
              builder: (context, constraints) {
                final totalWidth = constraints.maxWidth;
                const minChatWidth = 300.0;
                const minInspectorWidth = 250.0;

                double chatWidth = totalWidth * _chatFraction;
                if (chatWidth < minChatWidth) {
                  chatWidth = minChatWidth;
                }
                if (totalWidth - chatWidth - 8 < minInspectorWidth) {
                  chatWidth = totalWidth - minInspectorWidth - 8;
                }

                return Row(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    SizedBox(width: chatWidth, child: bodyContent),
                    GestureDetector(
                      behavior: HitTestBehavior.translucent,
                      onHorizontalDragUpdate: (details) {
                        setState(() {
                          _chatFraction =
                              (chatWidth + details.delta.dx) / totalWidth;
                          if (_chatFraction < 0.2) _chatFraction = 0.2;
                          if (_chatFraction > 0.85) _chatFraction = 0.85;
                        });
                      },
                      child: MouseRegion(
                        cursor: SystemMouseCursors.resizeLeftRight,
                        child: Container(
                          width: 8,
                          color: theme.dividerColor.withValues(alpha: 0.1),
                          child: Center(
                            child: Container(
                              width: 1,
                              color: theme.dividerColor,
                            ),
                          ),
                        ),
                      ),
                    ),
                    Expanded(
                      child: AgentInspector(
                        controller: _controller,
                      ),
                    ),
                  ],
                );
              },
            )
          : bodyContent,
    );
  }

  List<Widget> _buildAppBarActions(BuildContext context) {
    final l10n = _l10n;
    final isWide = MediaQuery.sizeOf(context).width >= 600;

    if (isWide) {
      return [
        IconButton(
          icon: const Icon(Icons.restart_alt),
          tooltip: l10n.get('resetTooltip'),
          onPressed: _resetPlayground,
        ),
        if (!_playgroundStarted) ...[
          IconButton(
            icon: const Icon(Icons.delete_sweep_outlined),
            tooltip: l10n.get('clearTooltip'),
            onPressed: _clearSetupInputs,
          ),
          IconButton(
            icon: const Icon(Icons.alt_route),
            tooltip: 'Load Workflow',
            onPressed: _showLoadWorkflowDialog,
          ),
        ],
        IconButton(
          icon: const Icon(Icons.save_outlined),
          tooltip: 'Save Workflow',
          onPressed: _showSaveWorkflowDialog,
        ),
        const VerticalDivider(width: 16, indent: 12, endIndent: 12),
        IconButton(
          icon: const Icon(Icons.bookmarks_outlined),
          tooltip: 'Skills Manager',
          onPressed: _showSkillsManagerDialog,
        ),
        IconButton(
          icon: const Icon(Icons.auto_awesome),
          tooltip: 'Skill Wizard',
          onPressed: _showSkillWizardDialog,
        ),
        const VerticalDivider(width: 16, indent: 12, endIndent: 12),
        IconButton(
          icon: const Icon(Icons.list_alt),
          tooltip: l10n.get('catalogTooltip'),
          onPressed: () => RegisteredToolsDialog.show(context, _controller),
        ),
        if (widget.showAgentInspector)
          IconButton(
            icon: Icon(
              _inspectorVisible
                  ? Icons.analytics
                  : Icons.analytics_outlined,
            ),
            tooltip: l10n.get('agentInspector'),
            onPressed: () {
              if (isWide && _playgroundStarted) {
                setState(() {
                  _inspectorVisible = !_inspectorVisible;
                });
              } else {
                _showAgentInspectorDialog();
              }
            },
          ),
      ];
    }

    return [
      IconButton(
        icon: const Icon(Icons.restart_alt),
        tooltip: l10n.get('resetTooltip'),
        onPressed: _resetPlayground,
      ),
      PopupMenuButton<String>(
        icon: const Icon(Icons.more_vert),
        tooltip: l10n.get('moreActions'),
        onSelected: (val) {
          if (val == 'clear') {
            _clearSetupInputs();
          } else if (val == 'saveWorkflow') {
            _showSaveWorkflowDialog();
          } else if (val == 'loadWorkflow') {
            _showLoadWorkflowDialog();
          } else if (val == 'skillsManager') {
            _showSkillsManagerDialog();
          } else if (val == 'skillWizard') {
            _showSkillWizardDialog();
          } else if (val == 'catalog') {
            RegisteredToolsDialog.show(context, _controller);
          } else if (val == 'inspector') {
            _showAgentInspectorDialog();
          }
        },
        itemBuilder: (ctx) => [
          if (!_playgroundStarted) ...[
            PopupMenuItem(
              value: 'clear',
              child: Row(
                children: [
                  const Icon(Icons.delete_sweep_outlined, size: 20),
                  const SizedBox(width: 12),
                  Text(l10n.get('clearTooltip')),
                ],
              ),
            ),
            const PopupMenuItem(
              value: 'loadWorkflow',
              child: Row(
                children: [
                  Icon(Icons.alt_route, size: 20),
                  SizedBox(width: 12),
                  Text('Load Workflow'),
                ],
              ),
            ),
          ],
          const PopupMenuItem(
            value: 'saveWorkflow',
            child: Row(
              children: [
                Icon(Icons.save_outlined, size: 20),
                SizedBox(width: 12),
                Text('Save Workflow'),
              ],
            ),
          ),
          const PopupMenuDivider(),
          const PopupMenuItem(
            value: 'skillsManager',
            child: Row(
              children: [
                Icon(Icons.bookmarks_outlined, size: 20),
                SizedBox(width: 12),
                Text('Skills Manager'),
              ],
            ),
          ),
          const PopupMenuItem(
            value: 'skillWizard',
            child: Row(
              children: [
                Icon(Icons.auto_awesome, size: 20),
                SizedBox(width: 12),
                Text('Skill Wizard'),
              ],
            ),
          ),
          const PopupMenuDivider(),
          PopupMenuItem(
            value: 'catalog',
            child: Row(
              children: [
                const Icon(Icons.list_alt, size: 20),
                const SizedBox(width: 12),
                Text(l10n.get('catalogTooltip')),
              ],
            ),
          ),
          if (_playgroundStarted && widget.showAgentInspector)
            PopupMenuItem(
              value: 'inspector',
              child: Row(
                children: [
                  const Icon(Icons.analytics_outlined, size: 20),
                  const SizedBox(width: 12),
                  Text(l10n.get('agentInspector')),
                ],
              ),
            ),
        ],
      ),
    ];
  }

  Widget _buildSetupView(ThemeData theme) {
    final groups = _getToolsetGroups();
    final enabledGroups = groups.where((g) => _isToolsetEnabled(g)).toList();
    final l10n = _l10n;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Select Tools',
                    style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
                  ),
                  const SizedBox(height: 10),
                  if (enabledGroups.isEmpty) ...[
                    ElevatedButton.icon(
                      onPressed: _showToolChecklistDialog,
                      icon: const Icon(Icons.add),
                      label: const Text('Choose active tools/toolsets'),
                    ),
                    const SizedBox(height: 6),
                    const Text(
                      'No tools selected. Chat mode will be active.',
                      style: TextStyle(color: Colors.grey, fontSize: 12),
                    ),
                  ] else
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      crossAxisAlignment: WrapCrossAlignment.center,
                      children: [
                        ...enabledGroups.map((group) {
                          IconData icon = Icons.extension_outlined;
                          Color iconColor = theme.colorScheme.primary;
                          if (group.isExternal) {
                            icon = Icons.dns_outlined;
                            iconColor = Colors.orange;
                          } else if (group.isInstalled) {
                            icon = Icons.hub_outlined;
                            iconColor = Colors.teal;
                          }
                          return InputChip(
                            avatar: Icon(icon, size: 14, color: iconColor),
                            label: Text(
                              group.name,
                              style: const TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                            deleteIcon: const Icon(Icons.close, size: 14),
                            onDeleted: () {
                              setState(() {
                                final updated = Set<String>.from(_controller.enabledToolNames);
                                for (final t in group.tools) {
                                  updated.remove(t.name);
                                }
                                _controller.updateEnabledTools(updated);
                              });
                            },
                            onPressed: () {
                              _showIndividualToolsDialog(group);
                            },
                          );
                        }),
                        ActionChip(
                          avatar: const Icon(Icons.add, size: 14),
                          label: const Text(
                            'Select Tools',
                            style: TextStyle(fontSize: 12),
                          ),
                          onPressed: _showToolChecklistDialog,
                        ),
                      ],
                    ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 16),

          Card(
            child: Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 8.0,
                vertical: 4.0,
              ),
              child: CheckboxListTile(
                value: _chatMode,
                title: const Text(
                  'Chat mode',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 14,
                  ),
                ),
                subtitle: const Text(
                  'Direct LLM chat — no system prompt, no tools. Fastest for simple tasks.',
                  style: TextStyle(fontSize: 11),
                ),
                onChanged: (v) {
                  setState(() {
                    _chatMode = v ?? false;
                  });
                },
              ),
            ),
          ),
          const SizedBox(height: 16),

          if (!_chatMode) ...[
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'System Prompt',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
                ),
                if (_getActiveLlmConfig().isConfigured)
                  IconButton(
                    icon: _isGeneratingSystemPrompt
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : const Icon(Icons.auto_awesome_outlined, size: 20),
                    tooltip: 'Generate System Prompt',
                    onPressed: _isGeneratingSystemPrompt
                        ? null
                        : _generateSystemPrompt,
                  ),
              ],
            ),
            const SizedBox(height: 4),
            TextFormField(
              controller: _systemPromptCtrl,
              maxLines: 5,
              minLines: 2,
              decoration: const InputDecoration(
                hintText:
                    'Enter instructions, catalog rules, persona details, or system guidelines...',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 16),
          ],

          const Text(
            'LLM Configuration',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
          ),
          const SizedBox(height: 8),
          SegmentedButton<bool>(
            segments: [
              ButtonSegment(
                value: false,
                label: Text(
                  'LLM 1 (${_controller.llmConfig.model.isNotEmpty ? _controller.llmConfig.model : 'default'})',
                ),
                icon: const Icon(Icons.psychology_outlined),
              ),
              const ButtonSegment(
                value: true,
                label: Text('Custom LLM Override'),
                icon: Icon(Icons.tune_outlined),
              ),
            ],
            selected: {_useCustomLlm},
            onSelectionChanged: (val) {
              setState(() {
                _useCustomLlm = val.first;
                if (_useCustomLlm && _customModelCtrl.text.isEmpty) {
                  _applyLlmDefaults();
                }
              });
            },
          ),
          const SizedBox(height: 12),

          if (_useCustomLlm)
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Wrap(
                      alignment: WrapAlignment.spaceBetween,
                      crossAxisAlignment: WrapCrossAlignment.center,
                      spacing: 8,
                      runSpacing: 8,
                      children: [
                        const Text(
                          'Custom LLM Config',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 13,
                          ),
                        ),
                        OutlinedButton.icon(
                          onPressed: _applyLlmDefaults,
                          icon: const Icon(Icons.settings_backup_restore),
                          label: const Text('Apply defaults from settings'),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    LlmConfigForm(
                      provider: _customProvider,
                      onProviderChanged: (val) {
                        _customProviderCache[_customProvider] =
                            _CustomProviderCache(
                              model: _customModelCtrl.text,
                              apiKey: _customApiKeyCtrl.text,
                              baseUrl: _customBaseUrlCtrl.text,
                            );
                        final cached = _customProviderCache[val];
                        if (cached != null) {
                          _customModelCtrl.text = cached.model;
                          _customApiKeyCtrl.text = cached.apiKey;
                          _customBaseUrlCtrl.text = cached.baseUrl;
                        } else {
                          _customModelCtrl.clear();
                          _customApiKeyCtrl.clear();
                          _customBaseUrlCtrl.clear();
                        }
                        setState(() {
                          _customProvider = val;
                        });
                      },
                      modelCtrl: _customModelCtrl,
                      apiKeyCtrl: _customApiKeyCtrl,
                      baseUrlCtrl: _customBaseUrlCtrl,
                    ),
                  ],
                ),
              ),
            ),
          const SizedBox(height: 16),

          ActiveSkillBanner(controller: _controller),

          Text(
            l10n.get('initialPrompt'),
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
          ),
          const SizedBox(height: 8),
          SubPromptListEditor(
            controller: _initialPromptCtrl,
            chatMode: _chatMode,
            availableToolGroups: _getToolsetGroups()
                .where((g) => _isToolsetEnabled(g))
                .map(
                  (g) => ToolGroup(
                    name: g.name,
                    toolNames: g.tools.map((t) => t.name).toList(),
                  ),
                )
                .toList(),
            minLines: 2,
            maxLines: 8,
            hintText:
                'Enter an optional first message to execute immediately on launch...',
          ),
          const SizedBox(height: 16),

          SizedBox(
            height: 50,
            child: FilledButton.icon(
              icon: const Icon(Icons.play_arrow_rounded),
              label: const Text(
                'Start GenUI Agent Playground',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
              ),
              onPressed: _startPlayground,
            ),
          ),
          const SizedBox(height: 24),
        ],
      ),
    );
  }

  Widget _buildGenuiConversationView(ThemeData theme) {
    if (_genuiController == null) {
      return const Center(child: CircularProgressIndicator());
    }

    final isGenerating = _genuiController!.isGenerating;
    final groups = _getToolsetGroups();
    final enabledToolsCount = groups
        .expand((g) => g.tools)
        .where((t) => _controller.enabledToolNames.contains(t.name))
        .length;

    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          child: Wrap(
            alignment: WrapAlignment.spaceBetween,
            crossAxisAlignment: WrapCrossAlignment.center,
            spacing: 8,
            runSpacing: 8,
            children: [
              ActionChip(
                avatar: const Icon(Icons.edit_note, size: 16),
                label: const Text('System Prompt (tap to edit)'),
                onPressed: () {
                  final promptCtrl = TextEditingController(
                    text: _controller.systemPrompt,
                  );
                  showDialog(
                    context: context,
                    builder: (ctx) => AlertDialog(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16),
                      ),
                      title: const Row(
                        children: [
                          Icon(Icons.edit_note, color: Color(0xFF0067C0)),
                          SizedBox(width: 8),
                          Text('Edit System Prompt'),
                        ],
                      ),
                      content: SizedBox(
                        width: 700,
                        child: TextFormField(
                          controller: promptCtrl,
                          maxLines: 12,
                          minLines: 6,
                          decoration: const InputDecoration(
                            hintText:
                                'Enter instructions, catalog rules, persona details, or system guidelines...',
                            border: OutlineInputBorder(),
                          ),
                        ),
                      ),
                      actions: [
                        TextButton(
                          onPressed: () => Navigator.pop(ctx),
                          child: const Text('Cancel'),
                        ),
                        FilledButton(
                          onPressed: () {
                            setState(() {
                              _controller.systemPrompt = promptCtrl.text;
                              _systemPromptCtrl.text = promptCtrl.text;
                            });
                            Navigator.pop(ctx);
                          },
                          child: const Text('Save'),
                        ),
                      ],
                    ),
                  );
                },
              ),
              ActionChip(
                avatar: const Icon(Icons.build_circle_outlined, size: 16),
                label: Text('$enabledToolsCount tools selected'),
                onPressed: _showSelectedToolsDialog,
              ),
            ],
          ),
        ),
        const Divider(height: 1),

        Expanded(
          child: AnimatedBuilder(
            animation: _genuiController!,
            builder: (context, _) {
              final entries = _genuiController!.entries;
              if (entries.isEmpty) {
                return _buildWelcomeWidget(theme);
              }
              return ListView(
                controller: _scrollCtrl,
                padding: const EdgeInsets.only(bottom: 24),
                children: [
                  for (final entry in entries)
                    _buildGenuiEntry(context, entry, theme),
                ],
              );
            },
          ),
        ),
        if (isGenerating)
          Padding(
            padding: const EdgeInsets.symmetric(
              vertical: 8.0,
              horizontal: 16.0,
            ),
            child: Row(
              children: [
                const SizedBox(
                  width: 14,
                  height: 14,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
                const SizedBox(width: 8),
                Text(
                  'GenUI Agent is generating interactive widgets and tool calls...',
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: Colors.grey,
                  ),
                ),
              ],
            ),
          ),
        _buildInputBar(theme),
      ],
    );
  }

  Widget _buildGenuiEntry(
    BuildContext context,
    GenuiChatEntry entry,
    ThemeData theme,
  ) {
    final isDark = theme.brightness == Brightness.dark;

    switch (entry.kind) {
      case GenuiChatEntryKind.user:
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            mainAxisSize: MainAxisSize.min,
            children: [
              if (entry.attachments != null && entry.attachments!.isNotEmpty)
                Padding(
                  padding: const EdgeInsets.only(bottom: 4),
                  child: Wrap(
                    spacing: 6,
                    runSpacing: 4,
                    alignment: WrapAlignment.end,
                    children: [
                      for (final att in entry.attachments!)
                        Chip(
                          avatar: Icon(
                            att.mimeType.startsWith('image/')
                                ? Icons.image_outlined
                                : Icons.description_outlined,
                            size: 14,
                          ),
                          label: Text(att.name, style: const TextStyle(fontSize: 11)),
                          visualDensity: VisualDensity.compact,
                          padding: EdgeInsets.zero,
                        ),
                    ],
                  ),
                ),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  IconButton(
                    icon: Icon(
                      Icons.content_copy_outlined,
                      size: 14,
                      color: theme.colorScheme.onSurfaceVariant.withValues(alpha: 0.6),
                    ),
                    tooltip: 'Copy prompt',
                    visualDensity: VisualDensity.compact,
                    padding: const EdgeInsets.all(4),
                    constraints: const BoxConstraints(),
                    onPressed: () {
                      Clipboard.setData(ClipboardData(text: entry.text));
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text('Prompt copied to clipboard'),
                          duration: Duration(seconds: 1),
                        ),
                      );
                    },
                  ),
                  const SizedBox(width: 4),
                  Flexible(
                    child: Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: theme.colorScheme.primary.withValues(alpha: 0.12),
                        borderRadius: BorderRadius.circular(16),
                      ),
                      child: Text(entry.text),
                    ),
                  ),
                ],
              ),
            ],
          ),
        );
      case GenuiChatEntryKind.assistant:
        if (entry.text.trim().isEmpty) return const SizedBox.shrink();
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 16),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              CircleAvatar(
                radius: 14,
                backgroundColor: isDark
                    ? Colors.white.withValues(alpha: 0.1)
                    : theme.colorScheme.primaryContainer,
                child: Icon(
                  Icons.auto_awesome_rounded,
                  size: 16,
                  color: isDark
                      ? Colors.white
                      : theme.colorScheme.onPrimaryContainer,
                ),
              ),
              const SizedBox(width: 8),
              Flexible(
                child: Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isDark
                        ? Colors.white.withValues(alpha: 0.05)
                        : Colors.black.withValues(alpha: 0.04),
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(entry.text),
                      const SizedBox(height: 6),
                      Align(
                        alignment: Alignment.bottomRight,
                        child: InkWell(
                          onTap: () {
                            Clipboard.setData(ClipboardData(text: entry.text));
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text('Response copied to clipboard'),
                                duration: Duration(seconds: 1),
                              ),
                            );
                          },
                          borderRadius: BorderRadius.circular(4),
                          child: Padding(
                            padding: const EdgeInsets.all(4.0),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Icon(
                                  Icons.content_copy_outlined,
                                  size: 13,
                                  color: theme.colorScheme.onSurfaceVariant
                                      .withValues(alpha: 0.6),
                                ),
                                const SizedBox(width: 4),
                                Text(
                                  'Copy',
                                  style: TextStyle(
                                    fontSize: 10,
                                    color: theme.colorScheme.onSurfaceVariant
                                        .withValues(alpha: 0.6),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        );
      case GenuiChatEntryKind.surface:
        if (entry.surfaceId != null) {
          return Card(
            margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
            elevation: 2,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Surface(
                surfaceContext: _genuiController!.contextFor(entry.surfaceId!),
              ),
            ),
          );
        }
        return const SizedBox.shrink();
      case GenuiChatEntryKind.error:
        return Container(
          margin: const EdgeInsets.symmetric(vertical: 4, horizontal: 16),
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            color: theme.colorScheme.errorContainer,
            borderRadius: BorderRadius.circular(8),
          ),
          child: Text(
            entry.text,
            style: TextStyle(
              color: theme.colorScheme.onErrorContainer,
              fontFamily: 'monospace',
              fontSize: 12,
            ),
          ),
        );
    }
  }

  Widget _buildWelcomeWidget(ThemeData theme) {
    return Center(
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(
                Icons.auto_awesome_rounded,
                size: 72,
                color: theme.colorScheme.primary.withValues(alpha: 0.5),
              ),
              const SizedBox(height: 16),
              Text(
                'GenUI Playground Ready',
                style: theme.textTheme.titleLarge?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Interactive GenUI widgets will be dynamically rendered directly from agent responses and MCP tool calls.',
                textAlign: TextAlign.center,
                style: theme.textTheme.bodyMedium?.copyWith(color: Colors.grey),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildAttachmentPreviews() {
    if (_attachments.isEmpty) return const SizedBox.shrink();
    return Container(
      height: 50,
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: _attachments.length,
        itemBuilder: (ctx, idx) {
          final att = _attachments[idx];
          return Container(
            margin: const EdgeInsets.only(right: 8),
            child: InputChip(
              label: Text(att.name, style: const TextStyle(fontSize: 11)),
              onDeleted: () {
                setState(() {
                  _attachments.removeAt(idx);
                });
              },
            ),
          );
        },
      ),
    );
  }

  Widget _buildInputBar(ThemeData theme) {
    final isGen = _genuiController?.isGenerating ?? false;
    final showButton =
        _inputCtrl.text.isNotEmpty || _attachments.isNotEmpty || !isGen;

    return Container(
      decoration: BoxDecoration(
        color: theme.colorScheme.surface,
        border: Border(top: BorderSide(color: theme.dividerColor)),
      ),
      child: SafeArea(
        top: false,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ActiveSkillBanner(
                controller: _controller,
                padding: const EdgeInsets.only(bottom: 6.0),
              ),
              _buildAttachmentPreviews(),
              SubPromptListEditor(
                controller: _inputCtrl,
                chatMode: _chatMode,
                availableToolGroups: _getToolsetGroups()
                    .where((g) => _isToolsetEnabled(g))
                    .map(
                      (g) => ToolGroup(
                        name: g.name,
                        toolNames: g.tools.map((t) => t.name).toList(),
                      ),
                    )
                    .toList(),
                minLines: 1,
                maxLines: 6,
                hintText: isGen
                    ? 'GenUI Agent is working...'
                    : 'Ask the GenUI agent to render UI or run tools...',
              ),
              const SizedBox(height: 8),
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.attach_file_outlined),
                    tooltip: 'Attach Files / Images',
                    onPressed: isGen ? null : _pickAttachments,
                  ),
                  const Spacer(),
                  if (isGen)
                    const Padding(
                      padding: EdgeInsets.symmetric(horizontal: 12.0),
                      child: SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(strokeWidth: 2.5),
                      ),
                    )
                  else
                    IconButton(
                      icon: Icon(
                        Icons.send_rounded,
                        color: showButton &&
                                _controller.activeLlmConfig.isConfigured
                            ? theme.colorScheme.primary
                            : Colors.grey,
                      ),
                      onPressed: showButton &&
                              _controller.activeLlmConfig.isConfigured
                          ? _handleSend
                          : null,
                    ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _CustomProviderCache {
  final String model;
  final String apiKey;
  final String baseUrl;

  _CustomProviderCache({
    required this.model,
    required this.apiKey,
    required this.baseUrl,
  });
}

class _ToolsetGroup {
  final String name;
  final String description;
  final List<MCPTool> tools;
  final bool isExternal;
  final bool isInstalled;

  _ToolsetGroup({
    required this.name,
    required this.description,
    required this.tools,
    this.isExternal = false,
    this.isInstalled = false,
  });
}
