import 'package:material_ui/material_ui.dart';
import 'package:genui/genui.dart';

import 'genui_chat_controller.dart';

/// A self-contained chat view backed by a [McpGenuiChatController].
///
/// It renders the conversation transcript (user/assistant text), the active
/// GenUI surfaces generated by the model, and a text input for the next
/// message.
class GenuiChatView extends StatefulWidget {
  /// Creates a [GenuiChatView].
  const GenuiChatView({
    super.key,
    required this.controller,
    this.title = 'GenUI Chat',
    this.inputHint = 'Message',
  });

  /// The controller driving the conversation.
  final McpGenuiChatController controller;

  /// The title shown in the app bar.
  final String title;

  /// The hint text for the message input.
  final String inputHint;

  @override
  State<GenuiChatView> createState() => _GenuiChatViewState();
}

class _GenuiChatViewState extends State<GenuiChatView> {
  final TextEditingController _inputController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    widget.controller.addListener(_onControllerChanged);
  }

  @override
  void dispose() {
    widget.controller.removeListener(_onControllerChanged);
    _inputController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _onControllerChanged() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted || !_scrollController.hasClients) return;
      _scrollController.jumpTo(_scrollController.position.maxScrollExtent);
    });
  }

  void _send() {
    final text = _inputController.text;
    if (text.trim().isEmpty) return;
    widget.controller.sendMessage(text);
    _inputController.clear();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Column(
        children: [
          Expanded(child: _buildTranscript(context)),
          _buildInput(context),
        ],
      ),
    );
  }

  Widget _buildTranscript(BuildContext context) {
    return AnimatedBuilder(
      animation: widget.controller,
      builder: (context, _) {
        final entries = widget.controller.entries;
        final surfaceIds = widget.controller.activeSurfaceIds.toList();
        return ListView(
          controller: _scrollController,
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 12),
          children: [
            for (final entry in entries) _buildEntry(context, entry),
            for (final surfaceId in surfaceIds)
              _buildSurface(context, surfaceId),
          ],
        );
      },
    );
  }

  Widget _buildEntry(BuildContext context, GenuiChatEntry entry) {
    switch (entry.kind) {
      case GenuiChatEntryKind.user:
        return _bubble(context, entry.text, isUser: true);
      case GenuiChatEntryKind.assistant:
        if (entry.text.trim().isEmpty) return const SizedBox.shrink();
        return _bubble(context, entry.text, isUser: false);
      case GenuiChatEntryKind.surface:
        if (entry.surfaceId != null) {
          return _buildSurface(context, entry.surfaceId!);
        }
        return const SizedBox.shrink();
      case GenuiChatEntryKind.error:
        return Container(
          margin: const EdgeInsets.symmetric(vertical: 6, horizontal: 12),
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: Theme.of(
              context,
            ).colorScheme.errorContainer.withValues(alpha: 0.3),
            borderRadius: BorderRadius.circular(12),
          ),
          child: Text(
            entry.text,
            style: TextStyle(
              color: Theme.of(context).colorScheme.onErrorContainer,
              fontFamily: 'monospace',
              fontSize: 12,
            ),
          ),
        );
    }
  }

  Widget _bubble(BuildContext context, String text, {required bool isUser}) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 12),
      child: Row(
        mainAxisAlignment: isUser
            ? MainAxisAlignment.end
            : MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (!isUser) ...[
            CircleAvatar(
              radius: 14,
              backgroundColor: isDark
                  ? Colors.white.withValues(alpha: 0.1)
                  : theme.colorScheme.primaryContainer,
              child: Icon(
                Icons.smart_toy_outlined,
                size: 16,
                color: isDark
                    ? Colors.white
                    : theme.colorScheme.onPrimaryContainer,
              ),
            ),
            const SizedBox(width: 8),
          ],
          Flexible(
            child: Container(
              padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 14),
              decoration: BoxDecoration(
                color: isUser
                  ? theme.colorScheme.primary.withValues(alpha: 0.12)
                  : (isDark
                        ? Colors.white.withValues(alpha: 0.05)
                        : Colors.black.withValues(alpha: 0.04)),
                borderRadius: BorderRadius.circular(16),
              ),
              child: Text(text),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSurface(BuildContext context, String surfaceId) {
    return Card(
      margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Surface(surfaceContext: widget.controller.contextFor(surfaceId)),
      ),
    );
  }

  Widget _buildInput(BuildContext context) {
    return SafeArea(
      top: false,
      child: Padding(
        padding: const EdgeInsets.all(8),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Expanded(
              child: TextField(
                controller: _inputController,
                minLines: 1,
                maxLines: 5,
                textInputAction: TextInputAction.newline,
                onSubmitted: (_) => _send(),
                decoration: InputDecoration(
                  hintText: widget.inputHint,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                  ),
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 16,
                    vertical: 12,
                  ),
                ),
              ),
            ),
            const SizedBox(width: 8),
            AnimatedBuilder(
              animation: widget.controller,
              builder: (context, _) {
                final generating = widget.controller.isGenerating;
                return IconButton.filled(
                  onPressed: generating ? null : _send,
                  icon: generating
                      ? const SizedBox(
                          width: 18,
                          height: 18,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Icon(Icons.send),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
